export const ADMIN_ROUTER='/admin'
export const LOGIN_ROUTER='/login'
export const REGISTRATION_ROUTER='/registration'
export const SHOP_ROUTER='/'
export const BASKET_ROUTER='/basket'
export const DEVICE_ROUTER='/device'
export const RATING_ROUTER='/rating'
export const UPDATE_DEVICE_ROUTER='/update/device'